### ISSUE TITLE
Is this source code out of date with the docs from website?

### ISSUE THREAD

**Issue by aallbrig** [awsdocs/amazon-gamelift-developer-guide#5]
Hello! I'm learning AWS GameLift to build a multiplayer game I want to enjoy with friends. As I was following some instructions on [fleets-creating-anywhere](https://docs.aws.amazon.com/gamelift/latest/developerguide/fleets-creating-anywhere.html) I found an issue in a code snippet under the "Create a fleet" section in the AWS CLI region of the docs. No biggie -- I can fix it!

I scroll to the bottom of the page and click "Edit this page in GitHub." I'm sent to https://github.com/awsdocs/amazon-gamelift-developer-guide/tree/main/doc_source/fleets-creating-anywhere.md ; however, that page doesn't exist!

I searched for a few phrases from that page in this repo but couldn't find this page from the docs. Thus I have to ask... Is the source code in this repo out of date from what has been posted on the docs website?

**Comment by aallbrig** [comment]
Whomever reads this: the issue I saw is just a missing `\` in one of the AWS CLI commands.

Under the "Create a fleet" section in the AWS CLI region of the docs, on step 2 (starting with the text "Create an Anywhere fleet using the [create-fleet](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/gamelift/create-fleet.html) command..."

The command snippet reads
```bash
aws gamelift create-fleet \
    --name HardwareAnywhere \
    --compute-type ANYWHERE
    --locations custom-location-1
```
... but it should read...
```bash
aws gamelift create-fleet \
    --name HardwareAnywhere \
    --compute-type ANYWHERE \
    --locations custom-location-1
```

It's very minor and I'm sure most know how to fix it. That said it would be cool to be able to contribute help as I'm working my way through the docs. I wouldn't feel hurt if whoever looked into the out of date source code also wanted to fix this missing `\` ;)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
